services:

  postgresql:
    # JDBC_URL: 'jdbc:postgresql://localhost:5432/public'
    # USERNAME: 'root'
    # PASSWORD: 'root'
    image: postgres
    environment:
      POSTGRES_DB: public
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    command: postgres -c 'max_connections=1000'
    ports:
      - 5432:5432
